# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3/image_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16v3/image_service.proto\x12\rimage_service\"\x1c\n\x06\x44\x65tect\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\"\x1b\n\x08Response\x12\x0f\n\x07results\x18\x01 \x03(\t2P\n\rImageDetector\x12?\n\x0b\x44\x65tectImage\x12\x15.image_service.Detect\x1a\x17.image_service.Response\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'v3.image_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _DETECT._serialized_start=41
  _DETECT._serialized_end=69
  _RESPONSE._serialized_start=71
  _RESPONSE._serialized_end=98
  _IMAGEDETECTOR._serialized_start=100
  _IMAGEDETECTOR._serialized_end=180
# @@protoc_insertion_point(module_scope)
